name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt -e .
    - name: Run tests
      run: |
        pytest --black --cov=template_reverse
    - name: Upload coverage
      run: |
        bash <(curl -s https://codecov.io/bash)
        
